name = "prasun1111"
pages_build_output_dir = "out"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "prasun1111-comments-test"
database_id = "9359b0c5-a637-4ff5-9cf3-ee4c24ff3e77"
migrations_dir = "migrations"
