name = "prasun1111"
pages_build_output_dir = "out"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "prasun1111-comments"
database_id = "04c895d0-9bfb-44f8-9754-5a365a547735"
migrations_dir = "migrations"
